# Site settings
title: Owen's Blog on GitHub
email: owen_goodluck@163.com
description:  This blog records the life and work of Owen !
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://owengoodluck.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  owengoodluck

# Build settings
markdown: kramdown
encoding: utf-8
